### ISSUE TITLE
make_dataset error

### ISSUE THREAD

**Issue by HassankSalim** [TengdaHan/Convolutional_Sketch_Inversion#5]
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
100%|███████████████████████████████████████████| 13/13 [00:10<00:00,  1.25it/s]
((13143, 16, 16), 'is the shape of B&W images')
Using TensorFlow backend.
make_dataset.py:112: UserWarning: Update your `Model` call to the Keras 2 API: `Model(outputs=Tensor("bl..., inputs=Tensor("in...)`
  model = Model(input=base_model.input, output=base_model.get_layer('block2_conv2').output)
 7936/13143 [=================>............] - ETA: 6s

13143/13143 [==============================] - 16s 1ms/step
Traceback (most recent call last):
  File "make_dataset.py", line 179, in <module>
    check_HDF5(args.img_size)
  File "make_dataset.py", line 139, in check_HDF5
    data_color = hf["data"]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/group.py", line 167, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'data' doesn't exist)"

Can u help me

**Comment by TengdaHan** [comment]
I suggest you should firstly check your `.h5` file to determine where your data is stored (which key). You can either use python `h5py` module or using HDFView. `hf['Your_Key']` may be what you want.
